# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'
        
    - name: Version
      id: version
      uses: gittools/actions/gitversion/execute@v0.9.15
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
      
    - name: Package
      run: dotnet pack --no-build -p:PackageVersion=${{ steps.version.outputs.nuGetVersionV2 }} -c Release
      
    - name: Push
      run: dotnet nuget push ./Oakular.Stateful/bin/Release/Oakular.Stateful.${{ steps.version.outputs.nuGetVersionV2 }}.nupkg -k ${{ secrets.NUGET_API_KEY }}
